/**
 * Copyright 2023 AutoZone, Inc.
 * Content is confidential to and proprietary information of AutoZone, Inc., its
 * subsidiaries and affiliates.
 */

export const controlDeskData = [
  {
    location: 'Aerosol',
    tile1: [
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '1/4', assigned: 1, state: 'not-started' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '0/4', assigned: 0, state: 'empty' },
      { count: '1/4', assigned: 0, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '0/4', assigned: 0, state: 'empty' },
      { count: '4/4', assigned: 4, state: 'empty' },
    ],
    tile2: [
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '4/4', assigned: 4, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'not-started' },
      { count: '4/4', assigned: 4, state: 'complete' },
      { count: '0/4', assigned: 0, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '1/4', assigned: 0, state: 'empty' },
      { count: '1/4', assigned: 4, state: 'complete' },
    ],

    subzones: [
      {
        location: 'Subzone1',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'error' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
      {
        location: 'Subzone2',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
    ],
  },
  {
    location: 'Battery',
    tile1: [
      { count: '0/4', assigned: 1, state: 'un-assigned' },
      { count: '1/4', assigned: 4, state: 'not-started' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '0/4', assigned: 2, state: 'empty' },
      { count: '1/4', assigned: 1, state: 'error' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'complete' },
      { count: '4/4', assigned: 4, state: 'un-assigned' },
    ],
    tile2: [
      { count: '0/4', assigned: 1, state: 'un-assigned' },
      { count: '4/4', assigned: 4, state: 'not-started' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '4/4', assigned: 1, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'error' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '1/4', assigned: 1, state: 'un-assigned' },
      { count: '1/4', assigned: 4, state: 'un-assigned' },
    ],

    subzones: [
      {
        location: 'Subzone1',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'error' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
      {
        location: 'Subzone2',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
    ],
  },
  {
    location: 'Hard Parts',
    tile1: [
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],
    tile2: [
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],

    subzones: [
      {
        location: 'HBP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
        tile2: [
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HDP1',
        tile1: [
          { count: '4/4', vehicle: null, selector: null, state: 'completed' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'error' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HFP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HHP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HJP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HKP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HLP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
    ],
  },
  {
    location: 'Mezzanine',
    tile1: [
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '4/4', assigned: 1, state: 'in-progress' },
    ],
    tile2: [
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '4/4', assigned: 4, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'not-started' },
      { count: '4/4', assigned: 4, state: 'complete' },
      { count: '0/4', assigned: 0, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '1/4', assigned: 0, state: 'empty' },
      { count: '1/4', assigned: 4, state: 'complete' },
    ],

    subzones: [
      {
        location: 'Subzone1',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'error' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
      {
        location: 'Subzone2',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
    ],
  },
  {
    location: 'Oil',
    tile1: [
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],
    tile2: [
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'not-started' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'complete' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],

    subzones: [
      {
        location: 'HBP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
        tile2: [
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HDP1',
        tile1: [
          { count: '4/4', vehicle: null, selector: null, state: 'completed' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'error' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HFP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HHP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HJP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HKP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HLP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
    ],
  },
  {
    location: 'Reserves',
    tile1: [
      { count: '0/4', assigned: 1, state: 'un-assigned' },
      { count: '1/4', assigned: 4, state: 'not-started' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '0/4', assigned: 2, state: 'empty' },
      { count: '1/4', assigned: 1, state: 'error' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'complete' },
      { count: '4/4', assigned: 4, state: 'un-assigned' },
    ],
    tile2: [
      { count: '0/4', assigned: 1, state: 'un-assigned' },
      { count: '4/4', assigned: 4, state: 'not-started' },
      { count: '0/4', assigned: 1, state: 'in-progress' },
      { count: '4/4', assigned: 1, state: 'empty' },
      { count: '0/4', assigned: 1, state: 'error' },
      { count: '0/4', assigned: 1, state: 'empty' },
      { count: '1/4', assigned: 1, state: 'un-assigned' },
      { count: '1/4', assigned: 4, state: 'un-assigned' },
    ],

    subzones: [
      {
        location: 'Subzone1',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'error' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
      {
        location: 'Subzone2',
        tile1: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'un-assigned' },
        ],
      },
    ],
  },
  {
    location: 'Pick to Cart',
    tile1: [
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],
    tile2: [
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],

    subzones: [
      {
        location: 'HBP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
        tile2: [
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HDP1',
        tile1: [
          { count: '4/4', vehicle: null, selector: null, state: 'completed' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'error' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HFP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HHP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HJP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HKP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HLP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
    ],
  },
  {
    location: 'LTD',
    tile1: [
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '0/4', assigned: null, state: 'un-assigned' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],
    tile2: [
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'not-started' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'complete' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
      { count: '1/4', assigned: 1, state: 'in-progress' },
    ],

    subzones: [
      {
        location: 'HBP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
        tile2: [
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HDP1',
        tile1: [
          { count: '4/4', vehicle: null, selector: null, state: 'completed' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'error' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HFP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'APAL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HHP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
        ],
      },
      {
        location: 'HJP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HKP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'in-progress' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
      {
        location: 'HLP1',
        tile1: [
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: null, selector: null, state: 'un-assigned' },
          { count: '0/4', vehicle: 'APAL', selector: 'kwheeler', state: 'not-started' },
        ],
        tile2: [
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'not-started' },
          { count: '4/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '0/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'empty' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
          { count: '1/4', vehicle: 'HAPL', selector: 'kwheeler', state: 'complete' },
        ],
      },
    ],
  },
];

export const heatMapData = [
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'un-assigned' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'empty' },
    { state: 'complete' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'in-progress' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'un-assigned' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'un-assigned' },
    { state: 'complete' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'un-assigned' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'un-assigned' },
    { state: 'complete' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'complete' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'un-assigned' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'un-assigned' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'un-assigned' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'empty' },
    { state: 'complete' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'un-assigned' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'un-assigned' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'un-assigned' },
    { state: 'complete' },
  ],
  [
    { state: 'un-assigned' },
    { state: 'un-assigned' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'complete' },
  ],
  [
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
  ],
  [
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'not-started' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'not-started' },
    { state: 'not-started' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'empty' },
    { state: 'complete' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'complete' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'empty' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'empty' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'complete' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
  ],
  [
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
    { state: 'not-started' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
    { state: 'empty' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
  ],
  [
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'complete' },
    { state: 'complete' },
    { state: 'complete' },
  ],
  [
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'not-started' },
    { state: 'complete' },
    { state: 'in-progress' },
    { state: 'in-progress' },
    { state: 'empty' },
    { state: 'in-progress' },
  ],
];
