/**
 * Copyright 2023 AutoZone, Inc.
 * Content is confidential to and proprietary information of AutoZone, Inc., its
 * subsidiaries and affiliates.
 */

const PO_DASHBOARD_ROWS = [
  {
    priority: true,
    arrivalTime: new Date('03/07/23 10:16:00'),
    vendorName: 'Ring & Pinion Service Inc.',
    poNumber: 20738877,
    door: '',
    location: 'Yard',
    position: 'inYard',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Yard',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 7,
    pieces: 0,
    totalPices: 14,
    commodity: 'OIL',
    poType: 'LTL',
    skusWithFPS: 870,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
    ],
    status: 'READY_FOR_SIGNATURE',
    actionDropdown: true,
  },
  {
    priority: true,
    arrivalTime: new Date('03/07/23 10:59:00'),
    vendorName: 'Mahle Clevite Inc.',
    poNumber: 20733850,
    door: 'RC06',
    location: 'Aisle 19',
    position: 'dcLocation',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Aisle',
    receivingDoor: 'RC07',
    lines: 19,
    totalLines: 190,
    pieces: 184,
    totalPices: 387,
    commodity: 'OIL',
    poType: 'PO',
    skusWithFPS: 950,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'FGH',
        lastName: 'GHI',
      },
    ],
    status: 'RECEIVING_IN_PROGRESS',
    actionDropdown: true,
  },
  {
    priority: true,
    arrivalTime: new Date('03/06/23 14:55:00'),
    vendorName: 'Crismon Mechanical LLC.',
    poNumber: 20739387,
    door: '',
    location: 'Yard',
    position: 'inYard',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Yard',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 19,
    pieces: 0,
    totalPices: 38,
    commodity: 'OIL',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'JKL',
        lastName: 'KLM',
      },
    ],
    status: 'READY_FOR_FINALIZATION',
    actionDropdown: true,
  },
  {
    priority: true,
    arrivalTime: new Date('03/06/23 13:01:00'),
    vendorName: 'Shades Western Technology',
    poNumber: 20730091,
    door: 'RC08',
    location: 'Aisle 10',
    position: 'dcLocation',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Aisle',
    receivingDoor: 'RC07',
    lines: 95,
    totalLines: 177,
    pieces: 184,
    totalPices: 380,
    commodity: 'AERO',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
      {
        id: 3,
        firstName: 'EFG',
        lastName: 'FGH',
      },
      {
        id: 4,
        firstName: 'FGH',
        lastName: 'GHI',
      },
      {
        id: 5,
        firstName: 'GHI',
        lastName: 'HIJ',
      },
      {
        id: 6,
        firstName: 'HIJ',
        lastName: 'IJK',
      },
    ],
    status: 'RECEIVING_IN_PROGRESS',
    actionDropdown: true,
  },
  {
    priority: true,
    arrivalTime: new Date('03/06/23 14:13:00'),
    vendorName: 'Dana Limited',
    poNumber: 20739348,
    door: '',
    location: 'Yard',
    position: 'inYard',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Yard',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 503,
    pieces: 0,
    totalPices: 1005,
    commodity: 'OIL',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ZXY',
        lastName: 'ABC',
      },
    ],
    status: 'READY_FOR_SIGNATURE',
    actionDropdown: true,
  },
  {
    priority: true,
    arrivalTime: new Date('03/06/23 15:11:00'),
    vendorName: 'Glad USA LLC.',
    poNumber: 20737830,
    door: 'RC04',
    location: 'Aisle 16',
    position: 'dcLocation',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Aisle',
    receivingDoor: 'RC07',
    lines: 91,
    totalLines: 161,
    pieces: 184,
    totalPices: 311,
    commodity: 'OIL',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
      {
        id: 3,
        firstName: 'EFG',
        lastName: 'FGH',
      },
    ],
    status: 'RECEIVING_IN_PROGRESS',
    actionDropdown: true,
  },
  {
    priority: true,
    arrivalTime: new Date('03/06/23 14:32:00'),
    vendorName: 'ADC Solutions Auto LLC',
    poNumber: 20730349,
    door: 'RC07',
    location: 'Gate 14',
    position: 'dcLocation',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Gate',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 100,
    pieces: 0,
    totalPices: 200,
    commodity: 'BATT',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
    ],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
  {
    priority: false,
    arrivalTime: new Date('03/06/23 10:29:00'),
    vendorName: 'Motorcar Parts of America',
    poNumber: 20731203,
    door: '',
    location: 'Yard',
    position: 'inYard',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Yard',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 53,
    pieces: 0,
    totalPices: 109,
    commodity: 'AERO',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
    ],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
  {
    priority: false,
    arrivalTime: new Date('03/06/23 15:23:00'),
    vendorName: 'Borg Propulsion Systems',
    poNumber: 20733849,
    door: '',
    location: 'Aisle 8',
    position: 'dcLocation',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Aisle',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 196,
    pieces: 0,
    totalPices: 389,
    commodity: 'OIL',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
  {
    priority: false,
    arrivalTime: new Date('03/06/23 16:34:00'),
    vendorName: 'RB Distribution Inc.',
    poNumber: 20733705,
    door: '',
    location: 'Lane 8',
    position: 'dcLocation',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Lane',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 54,
    pieces: 0,
    totalPices: 109,
    commodity: 'BATT',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
  {
    priority: false,
    arrivalTime: new Date('03/06/23 09:18:00'),
    vendorName: 'Empirical Systems Inc.',
    poNumber: 20730283,
    door: '',
    location: 'Aisle 6',
    position: 'dcLocation',
    carrierName: 'US Express',
    trailerNumber: '5241',
    locationType: 'Aisle',
    receivingDoor: 'RC07',
    lines: 0,
    totalLines: 395,
    pieces: 0,
    totalPices: 783,
    commodity: 'OIL',
    poType: 'LTL',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'DEF',
        lastName: 'DEF',
      },
    ],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
];

const PO_DASHBOARD_ROWS_AGE_BREAKDOWN_72 = [
  {
    dividerLabel: '72 Hours',
    priority: false,
    arrivalTime: undefined,
    vendorName: '',
    poNumber: 720000000000000000,
    door: '',
    location: '',
    lines: undefined,
    totalLines: undefined,
    pieces: undefined,
    totalPices: undefined,
    commodity: '',
    poType: '',
    skusWithFPS: undefined,
    totalSkusWithFPS: undefined,
    users: [],
    status: '',
    actionDropdown: false,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/07/23 10:16:00'),
    vendorName: 'Ring & Pinion Service Inc.',
    poNumber: 20738877,
    door: '',
    location: 'Yard',
    lines: 0,
    totalLines: 7,
    pieces: 0,
    totalPices: 14,
    commodity: 'OIL',
    poType: 'LTL',
    skusWithFPS: 870,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
    ],
    status: 'READY_FOR_SIGNATURE',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/07/23 10:59:00'),
    vendorName: 'Mahle Clevite Inc.',
    poNumber: 20733850,
    door: 'RC06',
    location: 'Aisle 19',
    lines: 19,
    totalLines: 190,
    pieces: 184,
    totalPices: 387,
    commodity: 'OIL',
    poType: 'PO',
    skusWithFPS: 950,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'FGH',
        lastName: 'GHI',
      },
    ],
    status: 'RECEIVING_IN_PROGRESS',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 14:55:00'),
    vendorName: 'Crismon Mechanical LLC.',
    poNumber: 20739387,
    door: '',
    location: 'Yard',
    lines: 0,
    totalLines: 19,
    pieces: 0,
    totalPices: 38,
    commodity: 'OIL',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'JKL',
        lastName: 'KLM',
      },
    ],
    status: 'READY_FOR_FINALIZATION',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 13:01:00'),
    vendorName: 'Shades Western Technology',
    poNumber: 20730091,
    door: 'RC08',
    location: 'Aisle 10',
    lines: 95,
    totalLines: 177,
    pieces: 184,
    totalPices: 380,
    commodity: 'AERO',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
      {
        id: 3,
        firstName: 'EFG',
        lastName: 'FGH',
      },
      {
        id: 4,
        firstName: 'FGH',
        lastName: 'GHI',
      },
      {
        id: 5,
        firstName: 'GHI',
        lastName: 'HIJ',
      },
      {
        id: 6,
        firstName: 'HIJ',
        lastName: 'IJK',
      },
    ],
    status: 'RECEIVING_IN_PROGRESS',
    actionDropdown: true,
  },
];

const PO_DASHBOARD_ROWS_AGE_BREAKDOWN_48 = [
  {
    dividerLabel: '48 Hours',
    priority: false,
    arrivalTime: undefined,
    vendorName: '',
    poNumber: 480000000000000000,
    door: '',
    location: '',
    lines: undefined,
    totalLines: undefined,
    pieces: undefined,
    totalPices: undefined,
    commodity: '',
    poType: '',
    skusWithFPS: undefined,
    totalSkusWithFPS: undefined,
    users: [],
    status: '',
    actionDropdown: false,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 14:13:00'),
    vendorName: 'Dana Limited',
    poNumber: 20739348,
    door: '',
    location: 'Yard',
    lines: 0,
    totalLines: 503,
    pieces: 0,
    totalPices: 1005,
    commodity: 'OIL',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ZXY',
        lastName: 'ABC',
      },
    ],
    status: 'READY_FOR_SIGNATURE',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 15:11:00'),
    vendorName: 'Glad USA LLC.',
    poNumber: 20737830,
    door: 'RC04',
    location: 'Aisle 16',
    lines: 91,
    totalLines: 161,
    pieces: 184,
    totalPices: 311,
    commodity: 'OIL',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
      {
        id: 3,
        firstName: 'EFG',
        lastName: 'FGH',
      },
    ],
    status: 'RECEIVING_IN_PROGRESS',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 14:32:00'),
    vendorName: 'ADC Solutions Auto LLC',
    poNumber: 20730349,
    door: 'RC07',
    location: 'Gate 14',
    lines: 0,
    totalLines: 100,
    pieces: 0,
    totalPices: 200,
    commodity: 'BATT',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
    ],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 10:29:00'),
    vendorName: 'Motorcar Parts of America',
    poNumber: 20731203,
    door: '',
    location: 'Yard',
    lines: 0,
    totalLines: 53,
    pieces: 0,
    totalPices: 109,
    commodity: 'AERO',
    poType: 'DSD',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'ABC',
        lastName: 'BCD',
      },
      {
        id: 2,
        firstName: 'CDE',
        lastName: 'DEF',
      },
    ],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
];

const PO_DASHBOARD_ROWS_AGE_BREAKDOWN_24 = [
  {
    dividerLabel: '24 Hours',
    priority: false,
    arrivalTime: undefined,
    vendorName: '',
    poNumber: 240000000000000000,
    door: '',
    location: '',
    lines: undefined,
    totalLines: undefined,
    pieces: undefined,
    totalPices: undefined,
    commodity: '',
    poType: '',
    skusWithFPS: undefined,
    totalSkusWithFPS: undefined,
    users: [],
    status: '',
    actionDropdown: false,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 15:23:00'),
    vendorName: 'Borg Propulsion Systems',
    poNumber: 20733849,
    door: '',
    location: 'Aisle 8',
    lines: 0,
    totalLines: 196,
    pieces: 0,
    totalPices: 389,
    commodity: 'OIL',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 16:34:00'),
    vendorName: 'RB Distribution Inc.',
    poNumber: 20733705,
    door: '',
    location: 'Lane 8',
    lines: 0,
    totalLines: 54,
    pieces: 0,
    totalPices: 109,
    commodity: 'BATT',
    poType: 'PO',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
  {
    dividerLabel: undefined,
    priority: true,
    arrivalTime: new Date('03/06/23 09:18:00'),
    vendorName: 'Empirical Systems Inc.',
    poNumber: 20730283,
    door: '',
    location: 'Aisle 6',
    lines: 0,
    totalLines: 395,
    pieces: 0,
    totalPices: 783,
    commodity: 'OIL',
    poType: 'LTL',
    skusWithFPS: 1000,
    totalSkusWithFPS: 1000,
    users: [
      {
        id: 1,
        firstName: 'DEF',
        lastName: 'DEF',
      },
    ],
    status: 'NOT_STARTED',
    actionDropdown: true,
  },
];

const PO_DASHBOARD_SEARCH_SUGGESTIONS = [
  'Shades Western Technology • PO 20730091',
  'Shades Western Technology • PO 11923311',
  'Shades Western Technology • PO 20001234',
  'Shades Western Technology • PO 19237771',
];

const PO_DASHBOARD_SEARCH_ROWS = [
  {
    vendorName: 'Shades Western Tech.',
    priority: true,
    poType: 'PO',
    status: 'READY_FOR_SIGNATURE',
    poNumber: 20730091,
    door: 'RC07',
    location: 'Gate 6',
    arrivalTime: new Date('03/06/23 13:01:00'),
    users: [
      {
        id: 1,
        firstName: 'CDE',
        lastName: 'JKL',
      },
    ],
  },
  {
    vendorName: 'Shades Western Tech.',
    priority: false,
    poType: 'PO',
    status: 'NOT_STARTED',
    poNumber: 11923311,
    door: 'RC09',
    location: 'Gate 6',
    arrivalTime: new Date('03/06/23 13:01:00'),
    users: [
      {
        id: 1,
        firstName: 'BCD',
        lastName: 'RST',
      },
    ],
  },
  {
    vendorName: 'Shades Western Tech.',
    priority: false,
    poType: 'PO',
    status: 'NOT_STARTED',
    poNumber: 20001234,
    door: 'RC08',
    location: 'Gate 7',
    arrivalTime: new Date('03/06/23 13:01:00'),
    users: [
      {
        id: 1,
        firstName: 'KLM',
        lastName: 'LMN',
      },
    ],
  },
  {
    vendorName: 'Shades Western Tech.',
    priority: false,
    poType: 'PO',
    status: 'REMOVED',
    poNumber: 19237771,
    door: 'RC08',
    location: 'Gate 6',
    arrivalTime: new Date('03/06/23 13:01:00'),
    users: [],
  },
];

const PO_DETAILS_PRODUCT_ROWS = [
  {
    productName: 'ABS Control Module',
    putLocations: 'FPS-PBG2215D',
    sku: '000419004',
    partNumber: 'B75001',
    lines: 40,
    totalLines: 100,
    pieces: 198,
    totalPices: 200,
  },
  {
    productName: 'Bosch Ignition Coil',
    putLocations: 'FPS-PBG5221B',
    sku: '001141520',
    partNumber: 'DM100',
    lines: 162,
    totalLines: 150,
    pieces: 332,
    totalPices: 340,
  },
  {
    productName: 'WL Set M12X1.5 Under Hub',
    putLocations: 'FPS-PBG2713F',
    sku: '000566128',
    partNumber: 'EGR1010',
    lines: 38,
    totalLines: 50,
    pieces: 75,
    totalPices: 90,
  },
  {
    productName: 'Oxygen Sensor',
    putLocations: 'FPS-PBG2215D',
    sku: '000419004',
    partNumber: '800-20004',
    lines: 80,
    totalLines: 122,
    pieces: 250,
    totalPices: 245,
  },
  {
    productName: 'Bosch Spark Plug',
    putLocations: 'FPS-PBG5221B',
    sku: '001141520',
    partNumber: 'DM104',
    lines: 32,
    totalLines: 61,
    pieces: 127,
    totalPices: 125,
  },
];

const PO_TYPES = [
  {
    label: 'DSD',
    value: 'dsd',
    fullForm: '(Direct Store Delivery)',
  },
  {
    label: 'PO',
    value: 'po',
    fullForm: '(Standard Purchase Orders)',
  },
  {
    label: 'LTL',
    value: 'ltl',
    fullForm: '(Less-Than-Truckload)',
  },
  {
    label: 'LTD',
    value: 'ltd',
    fullForm: '(Long Tail Distribution)',
  },
];

const COMMODITY_TYPES = [
  {
    label: 'AERO (Aerosol)',
    value: 'AERO',
  },
  {
    label: 'BATT (Batteries)',
    value: 'BATT',
  },
  {
    label: 'CD1 (Crossdock 1)',
    value: 'CD1',
  },
  {
    label: 'CD2 (Crossdock 2)',
    value: 'CD2',
  },
  {
    label: 'DI53 (DI Container 53)',
    value: 'DI53',
  },
  {
    label: 'DSD (Direct Shipment)',
    value: 'DSD',
  },
  {
    label: 'DMG (Damaged)',
    value: 'DMG',
  },
  {
    label: 'FIXT (Fixtures)',
    value: 'FIXT',
  },
  {
    label: 'FSCN (Floor Stacked Con)',
    value: 'FSCN',
  },
  {
    label: 'GDRT',
    value: 'GDRT',
  },
  {
    label: 'HPRT (Hard Parts)',
    value: 'HPRT',
  },
  {
    label: 'IMPO (Direct Imports)',
    value: 'IMPO',
  },
  {
    label: 'LTL (Less than Truckload)',
    value: 'LTL',
  },
  {
    label: 'NEW (New Store)',
    value: 'NEW',
  },
  {
    label: 'OB (Outbound)',
    value: 'OB',
  },
  {
    label: 'OIL (Oil)',
    value: 'OIL',
  },
  {
    label: 'OILD (Oil Displays)',
    value: 'OILD',
  },
  {
    label: 'PART (Parts)',
    value: 'PART',
  },
];

const LOCATION_TYPES = [
  {
    label: 'Yard',
    value: 'Yard',
  },
  {
    label: 'Door',
    value: 'Door',
  },
  {
    label: 'Lane',
    value: 'Lane',
  },
  {
    label: 'Aisle',
    value: 'Aisle',
  },
];

const PO_CATEGORIES = [
  {
    label: 'All POs',
    value: 'AllPOs',
  },
  {
    label: 'Assigned POs',
    value: 'AssignedPOs',
  },
  {
    label: 'Unassigned POs',
    value: 'UnassignedPOs',
  },
];

const ARRIVAL_TIMES = [
  {
    label: 'Last 24 hours',
    value: 'last24Hours',
  },
  {
    label: '24-48 hours ago',
    value: '24-48HoursAgo',
  },
  {
    label: '48-72 hours ago',
    value: '48-72HoursAgo',
  },
  {
    label: '72+ hours ago',
    value: '72+HoursAgo',
  },
];

const LANES = [
  {
    label: 'LN1',
    value: 'LN1',
  },
  {
    label: 'LN2',
    value: 'LN2',
  },
  {
    label: 'LN3',
    value: 'LN3',
  },
  {
    label: 'LN4',
    value: 'LN4',
  },
  {
    label: 'LN5',
    value: 'LN5',
  },
  {
    label: 'LN6',
    value: 'LN6',
  },
  {
    label: 'LN7',
    value: 'LN7',
  },
  {
    label: 'LN8',
    value: 'LN8',
  },
  {
    label: 'LN9',
    value: 'LN9',
  },
];

const RECOMMENDED_ASSIGNEES = [
  {
    id: 1,
    firstName: 'ABC',
    lastName: 'BCD',
  },
  {
    id: 2,
    firstName: 'CDE',
    lastName: 'DEF',
  },
  {
    id: 3,
    firstName: 'EFG',
    lastName: 'FGH',
  },
  {
    id: 4,
    firstName: 'FGH',
    lastName: 'GHI',
  },
  {
    id: 5,
    firstName: 'GHI',
    lastName: 'HIJ',
  },
];

const ALL_ASSIGNEES = [
  {
    id: 1,
    firstName: 'ABC',
    lastName: 'BCD',
  },
  {
    id: 2,
    firstName: 'CDE',
    lastName: 'DEF',
  },
  {
    id: 3,
    firstName: 'EFG',
    lastName: 'FGH',
  },
  {
    id: 4,
    firstName: 'FGH',
    lastName: 'GHI',
  },
  {
    id: 5,
    firstName: 'GHI',
    lastName: 'HIJ',
  },
  {
    id: 6,
    firstName: 'HIJ',
    lastName: 'IJK',
  },
  {
    id: 7,
    firstName: 'IJK',
    lastName: 'KLM',
  },
  {
    id: 8,
    firstName: 'KLM',
    lastName: 'LMN',
  },
  {
    id: 9,
    firstName: 'LMN',
    lastName: 'MNO',
  },
  {
    id: 10,
    firstName: 'MNO',
    lastName: 'NOP',
  },
];

const SEARCH_PROPERTIES = {
  PO: {
    queryParam: 'po',
    search: 'search',
  },
};

export {
  PO_DASHBOARD_ROWS,
  PO_DASHBOARD_ROWS_AGE_BREAKDOWN_72,
  PO_DASHBOARD_ROWS_AGE_BREAKDOWN_48,
  PO_DASHBOARD_ROWS_AGE_BREAKDOWN_24,
  PO_DASHBOARD_SEARCH_SUGGESTIONS,
  PO_DASHBOARD_SEARCH_ROWS,
  PO_DETAILS_PRODUCT_ROWS,
  PO_TYPES,
  COMMODITY_TYPES,
  LOCATION_TYPES,
  ARRIVAL_TIMES,
  PO_CATEGORIES,
  LANES,
  RECOMMENDED_ASSIGNEES,
  ALL_ASSIGNEES,
  SEARCH_PROPERTIES,
};
